### ISSUE TITLE
Error Messages anstatt Console Ausgabe

### ISSUE THREAD

**Issue by felixkru** [felixkru/PP2023#10]
![image](https://github.com/felixkru/PP2023/assets/140727119/8cb02291-ad06-4027-84de-f8fd1c37b1bb)
Vorher habe ich eine Ausgabe in der Konsole bekommen, das scheint nicht mehr zu Funktionieren

**Comment by felixkru** [comment]
Das ist unabhängig davon welche Zahl ich bei "Cluster" eingebe, und auch ob ich Werte bei den Vektoren angebe.

**Comment by lk24dx** [comment]
gefixt
