### ISSUE TITLE
Invalid scale-configuration

### ISSUE THREAD

**Issue by lk24dx** [felixkru/PP2023#14]
In der Console erscheint eine Fehlermeldung: Invalid scale configuration for scale: xAxes
![Bildschirmfoto 2023-09-25 um 15 20 08](https://github.com/felixkru/PP2023/assets/117345153/527877f7-dac4-4ee2-a165-932929cfd040)

Kannst du dir das mal angucken, ob dem Chart noch Parameter fehlen?

**Comment by felixkru** [comment]
Ist behoben und kommt mit dem nächsten pull von PROG-18-chartjs
