### ISSUE TITLE
Überarbeitung Switch: local-remote Button

### ISSUE THREAD

**Issue by lk24dx** [felixkru/PP2023#26]
Den local-remote-Button bitte überarbeiten.
Bitte keine Bottstrap-Klassen-stylen.
Auch bitte das Label Dsing ohne JS steuern. 
Du kannst dich am switch-variables input orierntieren.

**Comment by DarianG19** [comment]
warum? will es nur nachvollziehen

**Comment by felixkru** [comment]
@DarianG19 @lk24dx Ist das hier erledigt? Falls ja macht den karren einmal zu.
