### ISSUE TITLE
Kein Ergebnis bei Dezimalzahlen.

### ISSUE THREAD

**Issue by felixkru** [felixkru/PP2023#47]
Wenn ein CSV File mit dezimalzahlen hochgeladen wird, scheint dieses nicht verarbeitet zu werden. Könnte am File reader liegen, oder auch daran, dass der Algorithmus mit den Werten nicht umgehen kann.

**Comment by lk24dx** [comment]
Liegt am File Reader @NoahKuse

**Comment by NoahKuse** [comment]
lag daran das die Macher der Bibliothek englisch sind. Hab jetzt alle Kommas die eingelesen werden in Punkte geändert dann gehts.

**Comment by lk24dx** [comment]
knallt dass dann nicht, wenn eine csv eingelesen wird, wenn du pauschal alles mit komma umwandelst?
