### ISSUE TITLE
Manuelle Eingabe mit drei Variablen scheint Fehlerhaft

### ISSUE THREAD

**Issue by felixkru** [felixkru/PP2023#54]
Wenn man bei der Manuellen Eingabe Datenpunkte mit drei Variablen angibt, dann ist es möglich, dass man bei zwei Datenpunkten trotzdem mit K=3 eine Berechnung durchführen kann. Das darf so nicht sein. Das Problem könnte an mehreren Stellen liegen.

**Comment by lk24dx** [comment]
Ich habe das jetzt noch mal getestet auf development. Ich konnte das dort nicht wirklich nachvollziehen, hatte immer die Fehlermeldung . Hast du ein Video oder so?

**Comment by felixkru** [comment]
Tritt bei mir jetzt auch nicht mehr auf, sehr interessant haha.
