### ISSUE TITLE
Fehlermeldung beim aktualisieren der Seite (Dev)

### ISSUE THREAD

**Issue by Fabiancomida** [felixkru/PP2023#55]
![grafik](https://github.com/felixkru/PP2023/assets/99880346/04e80ede-6123-4995-a6dc-c72407452f13)

**Comment by Fabiancomida** [comment]
Ist nur bei Firefox, bei Chrome kommt keine. Hat auch keine bemerkbare auswirkung

**Comment by lk24dx** [comment]
Das ist keine relevante Meldung. Sagt nur aus, dass die Schriftarten nicht vorgeladen werden. Könnte man fixen mit <link rel="preload" as="font" href="font.woff2" type="font/woff2" crossorigin="anonymous"> und dann noch die richtige src. Kann man nach ganz hinten stellen.
