### ISSUE TITLE
Aufgetretene Fehler beim hochladen von Test-Dateien in den Dev 13.10 16 Uhr

### ISSUE THREAD

**Issue by Fabiancomida** [felixkru/PP2023#58]
![image](https://github.com/felixkru/PP2023/assets/99880346/03f40f90-2f0a-4117-af25-8df6c4986e4b)
Fehlermeldung wenn Datei Sonderzeichen enthält

![image](https://github.com/felixkru/PP2023/assets/99880346/5ce2e335-97b6-4868-84ed-cec58dc470eb)
Fehlermeldung beim enthalten von Buchstaben

**Comment by lk24dx** [comment]
Noah du musst noch ne richtige User exception einbauen.
Und gib mir dann mal einen richtigen return zurück, wenn die Funktion fehlschlägt, sowas wie erro oder false damit ich meine Funktionen abbrechen kann.  
Und beide Dateien müssen ausgelesen werden können!
