### ISSUE TITLE
Timeout der API kommt instant

### ISSUE THREAD

**Issue by felixkru** [felixkru/PP2023#61]
In der aktuellen dev umgebung, kommt gelegentlich sofort beim drücken des Berechnen Buttons der Timeout error.
(bei meinen Tests mit CSV file und Remote berechnung). 
![image](https://github.com/felixkru/PP2023/assets/140727119/6a749312-92ac-4e1a-affb-2c209632a827)

**Comment by lk24dx** [comment]
Ist auf PROG-99 gelöst. Das Attribut des Aufgaben-Status hat sich von processing auf Data irgendwas geändert. Daher kommen nur Tasks ans Backend mit einer Bearbeitungszeit unter drei Sekunden. Habe das neue Attribut com BE-team übernommen.
